// packages/solid/src/index.ts
/**
 * Solid Adapter - Consolidated SolidJS primitives for Directive
 *
 * 16 active exports: useFact, useDerived, useDispatch, useSelector,
 * useWatch, useInspect, useRequirementStatus, useEvents, useExplain,
 * useConstraintStatus, useOptimisticUpdate, useDirective, useHistory,
 * createTypedHooks, useSuspenseRequirement, shallowEqual
 *
 * Signal factories: createDerivedSignal, createFactSignal
 */

import type {
  TraceOption,
  ErrorBoundaryConfig,
  InferDerivations,
  InferEvents,
  InferFacts,
  InferSelectorState,
  ModuleDef,
  ModuleSchema,
  ModulesMap,
  NamespacedSystem,
  Plugin,
  SingleModuleSystem,
  SystemSnapshot,
} from "@directive-run/core";
import {
  createRequirementStatusPlugin,
  createSystem,
} from "@directive-run/core";
import type { RequirementTypeStatus } from "@directive-run/core";
import {
  type ConstraintInfo,
  type InspectState,
  assertSystem,
  buildHistoryState,
  computeInspectState,
  createThrottle,
  defaultEquality,
  depsChanged,
  pickFacts,
  runTrackedSelector,
  shallowEqual,
} from "@directive-run/core/adapter-utils";
import { type Accessor, createSignal, onCleanup } from "solid-js";

// Re-export for convenience
export type { RequirementTypeStatus, InspectState, ConstraintInfo };
export { shallowEqual };

/** Type for the requirement status plugin return value */
export type StatusPlugin = ReturnType<typeof createRequirementStatusPlugin>;

// ============================================================================
// useFact — single key or multi key
// ============================================================================

/** Single key overload */
export function useFact<
  S extends ModuleSchema,
  K extends keyof InferFacts<S> & string,
>(
  system: SingleModuleSystem<S>,
  factKey: K,
): Accessor<InferFacts<S>[K] | undefined>;
/** Multi-key overload */
export function useFact<
  S extends ModuleSchema,
  K extends keyof InferFacts<S> & string,
>(
  system: SingleModuleSystem<S>,
  factKeys: K[],
): Accessor<Pick<InferFacts<S>, K>>;
/** Implementation */
export function useFact(
  // biome-ignore lint/suspicious/noExplicitAny: Implementation signature
  system: SingleModuleSystem<any>,
  keyOrKeys: string | string[],
): Accessor<unknown> {
  assertSystem("useFact", system);
  if (
    process.env.NODE_ENV !== "production" &&
    typeof keyOrKeys === "function"
  ) {
    console.error(
      "[Directive] useFact() received a function. Did you mean useSelector()? " +
        "useFact() takes a string key or array of keys, not a selector function.",
    );
  }

  // Multi-key path
  if (Array.isArray(keyOrKeys)) {
    return _useFactMulti(system, keyOrKeys);
  }

  // Single key path
  return _useFactSingle(system, keyOrKeys);
}

// biome-ignore lint/suspicious/noExplicitAny: Internal
function _useFactSingle(
  system: SingleModuleSystem<any>,
  factKey: string,
): Accessor<unknown> {
  if (process.env.NODE_ENV !== "production") {
    if (!system.facts.$store.has(factKey)) {
      console.warn(
        `[Directive] useFact("${factKey}") — fact not found in store. ` +
          `Check that "${factKey}" is defined in your module's schema.`,
      );
    }
  }

  const [value, setValue] = createSignal(system.facts.$store.get(factKey));
  const unsubscribe = system.facts.$store.subscribe([factKey], () => {
    setValue(() => system.facts.$store.get(factKey));
  });
  onCleanup(unsubscribe);
  return value;
}

// biome-ignore lint/suspicious/noExplicitAny: Internal
function _useFactMulti(
  system: SingleModuleSystem<any>,
  factKeys: string[],
): Accessor<Record<string, unknown>> {
  const getValues = (): Record<string, unknown> => {
    const result: Record<string, unknown> = {};
    for (const key of factKeys) {
      result[key] = system.facts.$store.get(key);
    }
    return result;
  };
  const [state, setState] = createSignal(getValues());
  const unsubscribe = system.facts.$store.subscribe(factKeys, () => {
    setState(getValues);
  });
  onCleanup(unsubscribe);
  return state;
}

// ============================================================================
// useDerived — single key or multi key
// ============================================================================

/** Single key overload */
export function useDerived<
  S extends ModuleSchema,
  K extends keyof InferDerivations<S> & string,
>(
  system: SingleModuleSystem<S>,
  derivationId: K,
): Accessor<InferDerivations<S>[K]>;
/** Multi-key overload */
export function useDerived<
  S extends ModuleSchema,
  K extends keyof InferDerivations<S> & string,
>(
  system: SingleModuleSystem<S>,
  derivationIds: K[],
): Accessor<Pick<InferDerivations<S>, K>>;
/** Implementation */
export function useDerived(
  // biome-ignore lint/suspicious/noExplicitAny: Implementation signature
  system: SingleModuleSystem<any>,
  idOrIds: string | string[],
): Accessor<unknown> {
  assertSystem("useDerived", system);
  if (process.env.NODE_ENV !== "production" && typeof idOrIds === "function") {
    console.error(
      "[Directive] useDerived() received a function. Did you mean useSelector()? " +
        "useDerived() takes a string key or array of keys, not a selector function.",
    );
  }

  // Multi-key path
  if (Array.isArray(idOrIds)) {
    return _useDerivedMulti(system, idOrIds);
  }

  // Single key path
  return _useDerivedSingle(system, idOrIds);
}

// biome-ignore lint/suspicious/noExplicitAny: Internal
function _useDerivedSingle(
  system: SingleModuleSystem<any>,
  derivationId: string,
): Accessor<unknown> {
  if (process.env.NODE_ENV !== "production") {
    const initialValue = system.read(derivationId);
    if (initialValue === undefined) {
      console.warn(
        `[Directive] useDerived("${derivationId}") returned undefined. ` +
          `Check that "${derivationId}" is defined in your module's derive property.`,
      );
    }
  }
  const [value, setValue] = createSignal(system.read(derivationId));
  const unsubscribe = system.subscribe([derivationId], () => {
    setValue(() => system.read(derivationId));
  });
  onCleanup(unsubscribe);
  return value;
}

// biome-ignore lint/suspicious/noExplicitAny: Internal
function _useDerivedMulti(
  system: SingleModuleSystem<any>,
  derivationIds: string[],
): Accessor<Record<string, unknown>> {
  const getValues = (): Record<string, unknown> => {
    const result: Record<string, unknown> = {};
    for (const id of derivationIds) {
      result[id] = system.read(id);
    }
    return result;
  };
  const [state, setState] = createSignal(getValues());
  const unsubscribe = system.subscribe(derivationIds, () => {
    setState(getValues);
  });
  onCleanup(unsubscribe);
  return state;
}

// ============================================================================
// useSelector — auto-tracking selector over facts and derivations
// ============================================================================

/**
 * Auto-tracking selector over facts and derivations.
 * Uses `withTracking()` to detect which facts the selector accesses,
 * then subscribes only to those keys.
 */
export function useSelector<S extends ModuleSchema, R>(
  system: SingleModuleSystem<S>,
  selector: (state: InferSelectorState<S>) => R,
  equalityFn?: (a: R, b: R) => boolean,
): Accessor<R>;
export function useSelector(
  // biome-ignore lint/suspicious/noExplicitAny: Implementation signature
  system: SingleModuleSystem<any>,
  // biome-ignore lint/suspicious/noExplicitAny: Implementation signature
  selector: (state: any) => unknown,
  equalityFn: (a: unknown, b: unknown) => boolean = defaultEquality,
): Accessor<unknown> {
  assertSystem("useSelector", system);
  const deriveKeySet = new Set(Object.keys(system.derive ?? {}));

  // Build a tracking-aware state proxy that exposes both facts and derivations
  const runWithTracking = () =>
    runTrackedSelector(system, deriveKeySet, selector);

  const initial = runWithTracking();
  let trackedFactKeys = initial.factKeys;
  let trackedDeriveKeys = initial.deriveKeys;
  const [selected, setSelected] = createSignal(initial.value);

  const unsubs: Array<() => void> = [];

  const resubscribe = () => {
    for (const unsub of unsubs) unsub();
    unsubs.length = 0;

    const onUpdate = () => {
      const result = runWithTracking();
      setSelected((prev) => {
        if (!equalityFn(prev, result.value)) return result.value;
        return prev;
      });
      // Re-track: check if deps changed
      if (
        depsChanged(
          trackedFactKeys,
          result.factKeys,
          trackedDeriveKeys,
          result.deriveKeys,
        )
      ) {
        trackedFactKeys = result.factKeys;
        trackedDeriveKeys = result.deriveKeys;
        resubscribe();
      }
    };

    if (trackedFactKeys.length > 0) {
      unsubs.push(system.facts.$store.subscribe(trackedFactKeys, onUpdate));
    } else if (trackedDeriveKeys.length === 0) {
      unsubs.push(system.facts.$store.subscribeAll(onUpdate));
    }
    if (trackedDeriveKeys.length > 0) {
      unsubs.push(system.subscribe(trackedDeriveKeys, onUpdate));
    }
  };

  resubscribe();

  onCleanup(() => {
    for (const unsub of unsubs) unsub();
  });

  return selected;
}

// ============================================================================
// useDispatch
// ============================================================================

export function useDispatch<S extends ModuleSchema>(
  system: SingleModuleSystem<S>,
): (event: InferEvents<S>) => void {
  assertSystem("useDispatch", system);
  return (event: InferEvents<S>) => {
    system.dispatch(event);
  };
}

// ============================================================================
// useEvents — memoized events reference
// ============================================================================

/**
 * Returns the system's events dispatcher.
 */
export function useEvents<S extends ModuleSchema>(
  system: SingleModuleSystem<S>,
): SingleModuleSystem<S>["events"] {
  assertSystem("useEvents", system);
  return system.events;
}

// ============================================================================
// useWatch — derivation or fact side-effect
// ============================================================================

/** Watch a derivation or fact by key (auto-detected). When a key exists in both facts and derivations, the derivation overload takes priority. */
export function useWatch<
  S extends ModuleSchema,
  K extends keyof InferDerivations<S> & string,
>(
  system: SingleModuleSystem<S>,
  key: K,
  callback: (
    newValue: InferDerivations<S>[K],
    previousValue: InferDerivations<S>[K] | undefined,
  ) => void,
): void;
/** Watch a fact key with auto-detection. */
export function useWatch<
  S extends ModuleSchema,
  K extends keyof InferFacts<S> & string,
>(
  system: SingleModuleSystem<S>,
  key: K,
  callback: (
    newValue: InferFacts<S>[K] | undefined,
    previousValue: InferFacts<S>[K] | undefined,
  ) => void,
): void;
/** Implementation */
export function useWatch(
  // biome-ignore lint/suspicious/noExplicitAny: Implementation signature
  system: SingleModuleSystem<any>,
  key: string,
  callback: (newValue: unknown, prevValue: unknown) => void,
): void {
  assertSystem("useWatch", system);

  const unsubscribe = system.watch(key, callback);
  onCleanup(unsubscribe);
}

// ============================================================================
// useInspect — consolidated inspection hook
// ============================================================================

/** Options for useInspect */
export interface UseInspectOptions {
  throttleMs?: number;
}

/**
 * Consolidated system inspection hook.
 * Returns Accessor<InspectState> with optional throttling.
 */
export function useInspect(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
  options?: UseInspectOptions,
): Accessor<InspectState> {
  assertSystem("useInspect", system);
  const [state, setState] = createSignal<InspectState>(
    computeInspectState(system),
  );

  const update = () => {
    setState(computeInspectState(system));
  };

  if (options?.throttleMs && options.throttleMs > 0) {
    const { throttled, cleanup } = createThrottle(update, options.throttleMs);
    const unsubFacts = system.facts.$store.subscribeAll(throttled);
    const unsubSettled = system.onSettledChange(throttled);
    onCleanup(() => {
      cleanup();
      unsubFacts();
      unsubSettled();
    });
  } else {
    const unsubFacts = system.facts.$store.subscribeAll(update);
    const unsubSettled = system.onSettledChange(update);
    onCleanup(() => {
      unsubFacts();
      unsubSettled();
    });
  }

  return state;
}

// ============================================================================
// useRequirementStatus — single or multi
// ============================================================================

/** Single type overload */
export function useRequirementStatus(
  statusPlugin: StatusPlugin,
  type: string,
): Accessor<RequirementTypeStatus>;
/** Multi-type overload */
export function useRequirementStatus(
  statusPlugin: StatusPlugin,
  types: string[],
): Accessor<Record<string, RequirementTypeStatus>>;
/** Implementation */
export function useRequirementStatus(
  statusPlugin: StatusPlugin,
  typeOrTypes: string | string[],
):
  | Accessor<RequirementTypeStatus>
  | Accessor<Record<string, RequirementTypeStatus>> {
  if (Array.isArray(typeOrTypes)) {
    const getValues = (): Record<string, RequirementTypeStatus> => {
      const result: Record<string, RequirementTypeStatus> = {};
      for (const type of typeOrTypes) {
        result[type] = statusPlugin.getStatus(type);
      }
      return result;
    };
    const [state, setState] = createSignal(getValues());
    const unsubscribe = statusPlugin.subscribe(() => {
      setState(getValues);
    });
    onCleanup(unsubscribe);
    return state;
  }

  const [status, setStatus] = createSignal<RequirementTypeStatus>(
    statusPlugin.getStatus(typeOrTypes),
  );
  const unsubscribe = statusPlugin.subscribe(() => {
    setStatus(statusPlugin.getStatus(typeOrTypes));
  });
  onCleanup(unsubscribe);
  return status;
}

// ============================================================================
// useExplain — reactive requirement explanation
// ============================================================================

/**
 * Reactively returns the explanation string for a requirement.
 */
export function useExplain(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
  requirementId: string,
): Accessor<string | null> {
  assertSystem("useExplain", system);
  const [explanation, setExplanation] = createSignal<string | null>(
    system.explain(requirementId),
  );

  const update = () => setExplanation(system.explain(requirementId));
  const unsubFacts = system.facts.$store.subscribeAll(update);
  const unsubSettled = system.onSettledChange(update);
  onCleanup(() => {
    unsubFacts();
    unsubSettled();
  });

  return explanation;
}

// ============================================================================
// useConstraintStatus — reactive constraint inspection
// ============================================================================

/** Get all constraints */
export function useConstraintStatus(
  system: SingleModuleSystem<any>,
): Accessor<ConstraintInfo[]>;
/** Get a single constraint by ID */
export function useConstraintStatus(
  system: SingleModuleSystem<any>,
  constraintId: string,
): Accessor<ConstraintInfo | null>;
/** Implementation */
export function useConstraintStatus(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
  constraintId?: string,
): Accessor<ConstraintInfo[] | ConstraintInfo | null> {
  assertSystem("useConstraintStatus", system);
  const getVal = () => {
    const inspection = system.inspect();
    if (!constraintId) return inspection.constraints;
    return (
      inspection.constraints.find(
        (c: ConstraintInfo) => c.id === constraintId,
      ) ?? null
    );
  };

  const [state, setState] = createSignal<
    ConstraintInfo[] | ConstraintInfo | null
  >(getVal());

  const update = () => setState(getVal);
  const unsubFacts = system.facts.$store.subscribeAll(update);
  const unsubSettled = system.onSettledChange(update);
  onCleanup(() => {
    unsubFacts();
    unsubSettled();
  });

  return state;
}

// ============================================================================
// useOptimisticUpdate — batch with rollback on failure
// ============================================================================

export interface OptimisticUpdateResult {
  mutate: (updateFn: () => void) => void;
  isPending: Accessor<boolean>;
  error: Accessor<Error | null>;
  rollback: () => void;
}

/**
 * Optimistic update hook. Saves a snapshot before mutating, monitors
 * a requirement type via statusPlugin, and rolls back on failure.
 */
export function useOptimisticUpdate(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
  statusPlugin?: StatusPlugin,
  requirementType?: string,
): OptimisticUpdateResult {
  assertSystem("useOptimisticUpdate", system);
  const [isPending, setIsPending] = createSignal(false);
  const [error, setError] = createSignal<Error | null>(null);
  let snapshot: SystemSnapshot | null = null;
  let statusUnsub: (() => void) | null = null;

  const rollback = () => {
    if (snapshot) {
      system.restore(snapshot);
      snapshot = null;
    }
    setIsPending(false);
    setError(null);
    statusUnsub?.();
    statusUnsub = null;
  };

  const mutate = (updateFn: () => void) => {
    snapshot = system.getSnapshot();
    setIsPending(true);
    setError(null);
    system.batch(updateFn);

    if (statusPlugin && requirementType) {
      statusUnsub?.();
      statusUnsub = statusPlugin.subscribe(() => {
        const status = statusPlugin.getStatus(requirementType);
        if (!status.isLoading && !status.hasError) {
          snapshot = null;
          setIsPending(false);
          statusUnsub?.();
          statusUnsub = null;
        } else if (status.hasError) {
          setError(() => status.lastError);
          rollback();
        }
      });
    }
  };

  onCleanup(() => {
    statusUnsub?.();
  });

  return { mutate, isPending, error, rollback };
}

// ============================================================================
// useSuspenseRequirement — Solid-specific Suspense integration
// ============================================================================

/**
 * Single type: throws a promise while the requirement is pending (Suspense).
 */
export function useSuspenseRequirement(
  statusPlugin: StatusPlugin,
  type: string,
): Accessor<RequirementTypeStatus>;
/**
 * Multi-type: throws a promise while any of the requirements are pending.
 */
export function useSuspenseRequirement(
  statusPlugin: StatusPlugin,
  types: string[],
): Accessor<Record<string, RequirementTypeStatus>>;
/** Implementation */
export function useSuspenseRequirement(
  statusPlugin: StatusPlugin,
  typeOrTypes: string | string[],
):
  | Accessor<RequirementTypeStatus>
  | Accessor<Record<string, RequirementTypeStatus>> {
  const types = Array.isArray(typeOrTypes) ? typeOrTypes : [typeOrTypes];

  // Check if any are still loading — if so, throw a promise
  const anyLoading = () =>
    types.some((t) => statusPlugin.getStatus(t).isLoading);

  if (anyLoading()) {
    throw new Promise<void>((resolve) => {
      const unsub = statusPlugin.subscribe(() => {
        if (!anyLoading()) {
          unsub();
          resolve();
        }
      });
    });
  }

  // Once resolved, return normal accessor
  if (Array.isArray(typeOrTypes)) {
    return useRequirementStatus(statusPlugin, typeOrTypes) as Accessor<
      Record<string, RequirementTypeStatus>
    >;
  }
  return useRequirementStatus(
    statusPlugin,
    typeOrTypes,
  ) as Accessor<RequirementTypeStatus>;
}

// ============================================================================
// useHistory — reactive history signal
// ============================================================================

/**
 * Reactive history signal. Returns an Accessor that updates
 * when snapshots are taken or navigation occurs.
 *
 * @example
 * ```tsx
 * const history = useHistory(system);
 * <button disabled={!history()?.canGoBack} onClick={() => history()?.goBack()}>Undo</button>
 * ```
 */
export function useHistory(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
): Accessor<ReturnType<typeof buildHistoryState>> {
  assertSystem("useHistory", system);
  const [state, setState] = createSignal<
    ReturnType<typeof buildHistoryState>
  >(buildHistoryState(system));
  const unsub = system.onHistoryChange(() =>
    setState(buildHistoryState(system)),
  );
  onCleanup(unsub);
  return state;
}

// ============================================================================
// Scoped System
// ============================================================================

/** Configuration for useDirective */
interface UseDirectiveConfig {
  // biome-ignore lint/suspicious/noExplicitAny: Plugin types vary
  plugins?: Plugin<any>[];
  trace?: TraceOption;
  errorBoundary?: ErrorBoundaryConfig;
  tickMs?: number;
  zeroConfig?: boolean;
  // biome-ignore lint/suspicious/noExplicitAny: Facts type varies
  initialFacts?: Record<string, any>;
  status?: boolean;
  /** Fact keys to subscribe to (omit for all) */
  facts?: string[];
  /** Derivation keys to subscribe to (omit for all) */
  derived?: string[];
}

/**
 * Create a scoped Directive system with automatic lifecycle management.
 * When no `facts` or `derived` keys are specified, subscribes to ALL
 * facts and derivations and returns reactive signals.
 *
 * @example
 * ```tsx
 * // Subscribe to everything
 * const { facts, derived, events, dispatch } = useDirective(counterModule);
 *
 * // Selective keys
 * const { facts, derived } = useDirective(counterModule, { facts: ["count"], derived: ["doubled"] });
 * ```
 */
export function useDirective<M extends ModuleSchema>(
  moduleDef: ModuleDef<M>,
  config?: UseDirectiveConfig,
) {
  const allPlugins = [...(config?.plugins ?? [])];
  let statusPlugin: StatusPlugin | undefined;

  if (config?.status) {
    const sp = createRequirementStatusPlugin();
    statusPlugin = sp;
    // biome-ignore lint/suspicious/noExplicitAny: Plugin generic issues
    allPlugins.push(sp.plugin as Plugin<any>);
  }

  // biome-ignore lint/suspicious/noExplicitAny: Required for overload compatibility
  const system = createSystem({
    module: moduleDef,
    plugins: allPlugins.length > 0 ? allPlugins : undefined,
    trace: config?.trace,
    errorBoundary: config?.errorBoundary,
    tickMs: config?.tickMs,
    zeroConfig: config?.zeroConfig,
    initialFacts: config?.initialFacts,
  } as any) as unknown as SingleModuleSystem<M>;

  // SSR guard: initialize facts for SSR rendering, start reconciliation only in the browser
  if (typeof window !== "undefined") {
    system.start();
  } else {
    system.initialize();
  }

  onCleanup(() => {
    system.destroy();
  });

  const factKeys = config?.facts;
  const derivedKeys = config?.derived;
  const subscribeAll = !factKeys && !derivedKeys;

  // Subscribe to facts
  const [factsState, setFactsState] = createSignal(
    subscribeAll
      ? (system.facts.$store.toObject() as InferFacts<M>)
      : (pickFacts(system, factKeys ?? []) as InferFacts<M>),
  );
  const unsubFacts = subscribeAll
    ? system.facts.$store.subscribeAll(() => {
        setFactsState(() => system.facts.$store.toObject() as InferFacts<M>);
      })
    : factKeys && factKeys.length > 0
      ? system.facts.$store.subscribe(factKeys, () => {
          setFactsState(() => pickFacts(system, factKeys) as InferFacts<M>);
        })
      : null;

  // Subscribe to derivations
  const allDerivationKeys = subscribeAll
    ? Object.keys(system.derive ?? {})
    : (derivedKeys ?? []);
  const getDerived = (): InferDerivations<M> => {
    const result: Record<string, unknown> = {};
    for (const key of allDerivationKeys) {
      result[key] = system.read(key);
    }
    return result as InferDerivations<M>;
  };
  const [derivedState, setDerivedState] = createSignal(getDerived());
  const unsubDerived =
    allDerivationKeys.length > 0
      ? system.subscribe(allDerivationKeys, () => {
          setDerivedState(getDerived);
        })
      : null;

  onCleanup(() => {
    unsubFacts?.();
    unsubDerived?.();
  });

  const events = system.events;
  const dispatch = (event: InferEvents<M>) => system.dispatch(event);

  return {
    system,
    facts: factsState as Accessor<InferFacts<M>>,
    derived: derivedState as Accessor<InferDerivations<M>>,
    events,
    dispatch,
    statusPlugin,
  };
}

// ============================================================================
// Signal Factories (for use outside components)
// ============================================================================

/**
 * Create a derivation signal outside of a component.
 */
export function createDerivedSignal<T>(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
  derivationId: string,
): [Accessor<T>, () => void] {
  const [value, setValue] = createSignal<T>(system.read(derivationId) as T);
  const unsubscribe = system.subscribe([derivationId], () => {
    setValue(() => system.read(derivationId) as T);
  });
  return [value, unsubscribe];
}

/**
 * Create a fact signal outside of a component.
 */
export function createFactSignal<T>(
  // biome-ignore lint/suspicious/noExplicitAny: Must work with any schema
  system: SingleModuleSystem<any>,
  factKey: string,
): [Accessor<T | undefined>, () => void] {
  const [value, setValue] = createSignal<T | undefined>(
    system.facts.$store.get(factKey) as T | undefined,
  );
  const unsubscribe = system.facts.$store.subscribe([factKey], () => {
    setValue(() => system.facts.$store.get(factKey) as T | undefined);
  });
  return [value, unsubscribe];
}

// ============================================================================
// Typed Hooks Factory
// ============================================================================

export function createTypedHooks<M extends ModuleSchema>(): {
  useFact: <K extends keyof InferFacts<M> & string>(
    system: SingleModuleSystem<M>,
    factKey: K,
  ) => Accessor<InferFacts<M>[K] | undefined>;
  useDerived: <K extends keyof InferDerivations<M> & string>(
    system: SingleModuleSystem<M>,
    derivationId: K,
  ) => Accessor<InferDerivations<M>[K]>;
  useDispatch: (
    system: SingleModuleSystem<M>,
  ) => (event: InferEvents<M>) => void;
  useEvents: (system: SingleModuleSystem<M>) => SingleModuleSystem<M>["events"];
  useWatch: <K extends string>(
    system: SingleModuleSystem<M>,
    key: K,
    callback: (newValue: unknown, previousValue: unknown) => void,
  ) => void;
} {
  return {
    useFact: <K extends keyof InferFacts<M> & string>(
      system: SingleModuleSystem<M>,
      factKey: K,
    ) =>
      // biome-ignore lint/suspicious/noExplicitAny: Required for overload compatibility
      useFact(system as SingleModuleSystem<any>, factKey as string) as Accessor<
        InferFacts<M>[K] | undefined
      >,
    useDerived: <K extends keyof InferDerivations<M> & string>(
      system: SingleModuleSystem<M>,
      derivationId: K,
    ) =>
      // biome-ignore lint/suspicious/noExplicitAny: Required for overload compatibility
      useDerived(
        system as SingleModuleSystem<any>,
        derivationId as string,
      ) as Accessor<InferDerivations<M>[K]>,
    useDispatch: (system: SingleModuleSystem<M>) => {
      return (event: InferEvents<M>) => {
        system.dispatch(event);
      };
    },
    useEvents: (system: SingleModuleSystem<M>) => useEvents<M>(system),
    useWatch: <K extends string>(
      system: SingleModuleSystem<M>,
      key: K,
      callback: (newValue: unknown, previousValue: unknown) => void,
    ) =>
      // biome-ignore lint/suspicious/noExplicitAny: Required for overload compatibility
      useWatch(system as SingleModuleSystem<any>, key, callback),
  };
}

// ============================================================================
// useNamespacedSelector — select from a NamespacedSystem
// ============================================================================

/**
 * SolidJS accessor that selects from a NamespacedSystem.
 * Subscribes to specified keys and provides reactive updates.
 *
 * @param system - The namespaced system
 * @param keys - Namespaced keys to subscribe to (e.g., ["auth.token", "data.count"])
 * @param selector - Function that reads from system.facts / system.derive
 *
 * @example
 * ```tsx
 * const token = useNamespacedSelector(system, ["auth.token"], (s) => s.facts.auth.token);
 * ```
 */
export function useNamespacedSelector<Modules extends ModulesMap, R>(
  system: NamespacedSystem<Modules>,
  keys: string[],
  selector: (system: NamespacedSystem<Modules>) => R,
): Accessor<R> {
  const [value, setValue] = createSignal<R>(selector(system));
  const unsubscribe = system.subscribe(keys, () => {
    setValue(() => selector(system));
  });
  onCleanup(unsubscribe);

  return value as Accessor<R>;
}

// packages/lit/src/index.ts
/**
 * Lit Adapter - Consolidated Web Components integration for Directive
 *
 * Controllers: DerivedController, FactController,
 * InspectController (with throttle), RequirementStatusController,
 * DirectiveSelectorController,
 * WatchController (with fact mode), SystemController,
 * ExplainController, ConstraintStatusController, OptimisticUpdateController, ModuleController
 *
 * Factories: createDerived, createFact, createInspect,
 * createRequirementStatus, createWatch,
 * createDirectiveSelector, useDispatch, useEvents, useTimeTravel,
 * getDerived, getFact, createTypedHooks, shallowEqual
 */

import type { ReactiveController, ReactiveControllerHost } from "lit";
import type {
	CreateSystemOptionsSingle,
	ModuleSchema,
	ModuleDef,
	Plugin,
	DebugConfig,
	ErrorBoundaryConfig,
	InferFacts,
	InferDerivations,
	InferEvents,
	SingleModuleSystem,
	SystemSnapshot,
	TimeTravelState,
} from "@directive-run/core";
import {
	createSystem,
	createRequirementStatusPlugin,
} from "@directive-run/core";
import type { RequirementTypeStatus } from "@directive-run/core";
import {
	type InspectState,
	type ConstraintInfo,
	type TrackedSelectorResult,
	computeInspectState,
	createThrottle,
	assertSystem,
	defaultEquality,
	buildTimeTravelState,
	runTrackedSelector,
	depsChanged,
	shallowEqual,
} from "@directive-run/core/adapter-utils";

// Re-export for convenience
export type { RequirementTypeStatus, InspectState, ConstraintInfo };
export { shallowEqual };

/** Type for the requirement status plugin return value */
export type StatusPlugin = ReturnType<typeof createRequirementStatusPlugin>;

// ============================================================================
// Context
// ============================================================================

/**
 * Context key for Directive system.
 * Use with @lit/context for dependency injection across shadow DOM boundaries.
 */
export const directiveContext = Symbol("directive");

// ============================================================================
// Base Controller
// ============================================================================

/**
 * Base controller that manages system subscription lifecycle.
 */
abstract class DirectiveController implements ReactiveController {
	protected host: ReactiveControllerHost;
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	protected system: SingleModuleSystem<any>;
	protected unsubscribe?: () => void;

	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	constructor(host: ReactiveControllerHost, system: SingleModuleSystem<any>) {
		this.host = host;
		this.system = system;
		host.addController(this);
	}

	hostConnected(): void {
		this.subscribe();
	}

	hostDisconnected(): void {
		this.unsubscribe?.();
		this.unsubscribe = undefined;
	}

	protected abstract subscribe(): void;

	protected requestUpdate(): void {
		this.host.requestUpdate();
	}
}

// ============================================================================
// Core Controllers
// ============================================================================

/**
 * Reactive controller for derivations.
 * Accepts a single key (string) or an array of keys (string[]).
 * - Single key: `.value` returns `T`
 * - Array of keys: `.value` returns `Record<string, unknown>`
 */
export class DerivedController<T> extends DirectiveController {
	private keys: string[];
	private isMulti: boolean;
	value: T;

	constructor(
		host: ReactiveControllerHost,
		// biome-ignore lint/suspicious/noExplicitAny: System type varies
		system: SingleModuleSystem<any>,
		key: string | string[],
	) {
		super(host, system);
		this.isMulti = Array.isArray(key);
		this.keys = this.isMulti ? (key as string[]) : [key as string];
		this.value = this.getValues();

		if (process.env.NODE_ENV !== "production") {
			if (!this.isMulti && this.value === undefined) {
				console.warn(
					`[Directive] DerivedController("${this.keys[0]}") returned undefined. ` +
					`Check that "${this.keys[0]}" is defined in your module's derive property.`,
				);
			}
		}
	}

	private getValues(): T {
		if (this.isMulti) {
			const result: Record<string, unknown> = {};
			for (const id of this.keys) {
				result[id] = this.system.read(id);
			}
			return result as T;
		}
		return this.system.read(this.keys[0]!) as T;
	}

	protected subscribe(): void {
		this.value = this.getValues();
		this.unsubscribe = this.system.subscribe(this.keys, () => {
			this.value = this.getValues();
			this.requestUpdate();
		});
	}
}

/**
 * Reactive controller for a single fact value.
 */
export class FactController<T> extends DirectiveController {
	private factKey: string;
	value: T | undefined;

	constructor(
		host: ReactiveControllerHost,
		// biome-ignore lint/suspicious/noExplicitAny: System type varies
		system: SingleModuleSystem<any>,
		factKey: string,
	) {
		super(host, system);
		this.factKey = factKey;
		this.value = system.facts.$store.get(factKey) as T | undefined;

		if (process.env.NODE_ENV !== "production") {
			if (!system.facts.$store.has(factKey)) {
				console.warn(
					`[Directive] FactController("${factKey}") — fact not found in store. ` +
					`Check that "${factKey}" is defined in your module's schema.`,
				);
			}
		}
	}

	protected subscribe(): void {
		this.value = this.system.facts.$store.get(this.factKey) as T | undefined;
		this.unsubscribe = this.system.facts.$store.subscribe(
			[this.factKey],
			() => {
				this.value = this.system.facts.$store.get(this.factKey) as T | undefined;
				this.requestUpdate();
			},
		);
	}
}

/**
 * Consolidated inspection controller.
 * Returns InspectState with optional throttling.
 */
export class InspectController extends DirectiveController {
	value: InspectState;
	private throttleMs: number;
	private throttleCleanup?: () => void;
	private unsubSettled?: () => void;

	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	constructor(host: ReactiveControllerHost, system: SingleModuleSystem<any>, options?: { throttleMs?: number }) {
		super(host, system);
		this.throttleMs = options?.throttleMs ?? 0;
		this.value = computeInspectState(system);
	}

	protected subscribe(): void {
		this.value = computeInspectState(this.system);

		const update = () => {
			this.value = computeInspectState(this.system);
			this.requestUpdate();
		};

		if (this.throttleMs > 0) {
			const { throttled, cleanup } = createThrottle(update, this.throttleMs);
			this.throttleCleanup = cleanup;
			this.unsubscribe = this.system.facts.$store.subscribeAll(throttled);
			this.unsubSettled = this.system.onSettledChange(throttled);
		} else {
			this.unsubscribe = this.system.facts.$store.subscribeAll(update);
			this.unsubSettled = this.system.onSettledChange(update);
		}
	}

	hostDisconnected(): void {
		this.throttleCleanup?.();
		this.unsubSettled?.();
		super.hostDisconnected();
	}
}

/**
 * Reactive controller for requirement status.
 */
export class RequirementStatusController implements ReactiveController {
	private host: ReactiveControllerHost;
	private statusPlugin: StatusPlugin;
	private type: string;
	private unsubscribe?: () => void;
	value: RequirementTypeStatus;

	constructor(
		host: ReactiveControllerHost,
		statusPlugin: StatusPlugin,
		type: string,
	) {
		this.host = host;
		this.statusPlugin = statusPlugin;
		this.type = type;
		this.value = statusPlugin.getStatus(type);
		host.addController(this);
	}

	hostConnected(): void {
		this.value = this.statusPlugin.getStatus(this.type);
		this.unsubscribe = this.statusPlugin.subscribe(() => {
			this.value = this.statusPlugin.getStatus(this.type);
			this.host.requestUpdate();
		});
	}

	hostDisconnected(): void {
		this.unsubscribe?.();
		this.unsubscribe = undefined;
	}
}

// ============================================================================
// Selector Controllers
// ============================================================================

/**
 * Reactive controller for selecting across all facts.
 * Uses `withTracking()` for auto-tracking when constructed with `autoTrack: true`.
 */
export class DirectiveSelectorController<R> extends DirectiveController {
	private selector: (state: Record<string, unknown>) => R;
	private equalityFn: (a: R, b: R) => boolean;
	private autoTrack: boolean;
	private deriveKeySet: Set<string>;
	private trackedFactKeys: string[] = [];
	private trackedDeriveKeys: string[] = [];
	private unsubs: Array<() => void> = [];
	value: R;

	constructor(
		host: ReactiveControllerHost,
		// biome-ignore lint/suspicious/noExplicitAny: System type varies
		system: SingleModuleSystem<any>,
		selector: (state: Record<string, unknown>) => R,
		equalityFn: (a: R, b: R) => boolean = defaultEquality,
		options?: { autoTrack?: boolean },
	) {
		super(host, system);
		this.selector = selector;
		this.equalityFn = equalityFn;
		this.autoTrack = options?.autoTrack ?? true;
		this.deriveKeySet = new Set(Object.keys(system.derive ?? {}));

		const initial = this.runWithTracking();
		this.value = initial.value;
		this.trackedFactKeys = initial.factKeys;
		this.trackedDeriveKeys = initial.deriveKeys;
	}

	private runWithTracking(): TrackedSelectorResult<R> {
		return runTrackedSelector(this.system, this.deriveKeySet, this.selector);
	}

	private resubscribe(): void {
		for (const unsub of this.unsubs) unsub();
		this.unsubs = [];

		const onUpdate = () => {
			const result = this.runWithTracking();
			if (!this.equalityFn(this.value, result.value)) {
				this.value = result.value;
				this.requestUpdate();
			}
			if (this.autoTrack) {
				// Re-track: check if deps changed
				if (depsChanged(this.trackedFactKeys, result.factKeys, this.trackedDeriveKeys, result.deriveKeys)) {
					this.trackedFactKeys = result.factKeys;
					this.trackedDeriveKeys = result.deriveKeys;
					this.resubscribe();
				}
			}
		};

		if (this.autoTrack) {
			if (this.trackedFactKeys.length > 0) {
				this.unsubs.push(this.system.facts.$store.subscribe(this.trackedFactKeys, onUpdate));
			} else if (this.trackedDeriveKeys.length === 0) {
				this.unsubs.push(this.system.facts.$store.subscribeAll(onUpdate));
			}
			if (this.trackedDeriveKeys.length > 0) {
				this.unsubs.push(this.system.subscribe(this.trackedDeriveKeys, onUpdate));
			}
		} else {
			this.unsubs.push(this.system.facts.$store.subscribeAll(onUpdate));
		}
	}

	protected subscribe(): void {
		const result = this.runWithTracking();
		this.value = result.value;
		this.trackedFactKeys = result.factKeys;
		this.trackedDeriveKeys = result.deriveKeys;
		this.resubscribe();
	}

	hostDisconnected(): void {
		for (const unsub of this.unsubs) unsub();
		this.unsubs = [];
		super.hostDisconnected();
	}
}

/**
 * Reactive controller that watches a fact or derivation and calls a callback on change.
 * The key is auto-detected — works with both fact keys and derivation keys.
 */
export class WatchController<T> extends DirectiveController {
	private key: string;
	private callback: (newValue: T, previousValue: T | undefined) => void;

	/** Watch a derivation or fact by key (auto-detected). When a key exists in both facts and derivations, the derivation overload takes priority. */
	constructor(
		host: ReactiveControllerHost,
		// biome-ignore lint/suspicious/noExplicitAny: System type varies
		system: SingleModuleSystem<any>,
		key: string,
		callback: (newValue: T, previousValue: T | undefined) => void,
	) {
		super(host, system);
		this.key = key;
		this.callback = callback;
	}

	protected subscribe(): void {
		this.unsubscribe = this.system.watch<T>(this.key, this.callback);
	}
}

// ============================================================================
// New Controllers
// ============================================================================

/**
 * Reactive controller for requirement explanations.
 */
export class ExplainController extends DirectiveController {
	private requirementId: string;
	value: string | null;
	private unsubSettled?: () => void;

	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	constructor(host: ReactiveControllerHost, system: SingleModuleSystem<any>, requirementId: string) {
		super(host, system);
		this.requirementId = requirementId;
		this.value = system.explain(requirementId);
	}

	protected subscribe(): void {
		this.value = this.system.explain(this.requirementId);

		const update = () => {
			this.value = this.system.explain(this.requirementId);
			this.requestUpdate();
		};

		this.unsubscribe = this.system.facts.$store.subscribeAll(update);
		this.unsubSettled = this.system.onSettledChange(update);
	}

	hostDisconnected(): void {
		this.unsubSettled?.();
		super.hostDisconnected();
	}
}

/**
 * Reactive controller for constraint status.
 */
export class ConstraintStatusController extends DirectiveController {
	private constraintId?: string;
	value: ConstraintInfo[] | ConstraintInfo | null;
	private unsubSettled?: () => void;

	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	constructor(host: ReactiveControllerHost, system: SingleModuleSystem<any>, constraintId?: string) {
		super(host, system);
		this.constraintId = constraintId;
		this.value = this.getVal();
	}

	private getVal(): ConstraintInfo[] | ConstraintInfo | null {
		const inspection = this.system.inspect();
		if (!this.constraintId) return inspection.constraints;
		return inspection.constraints.find((c: ConstraintInfo) => c.id === this.constraintId) ?? null;
	}

	protected subscribe(): void {
		this.value = this.getVal();

		const update = () => {
			this.value = this.getVal();
			this.requestUpdate();
		};

		this.unsubscribe = this.system.facts.$store.subscribeAll(update);
		this.unsubSettled = this.system.onSettledChange(update);
	}

	hostDisconnected(): void {
		this.unsubSettled?.();
		super.hostDisconnected();
	}
}

/**
 * Reactive controller for optimistic updates.
 */
export class OptimisticUpdateController implements ReactiveController {
	private host: ReactiveControllerHost;
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	private system: SingleModuleSystem<any>;
	private statusPlugin?: StatusPlugin;
	private requirementType?: string;
	private snapshot: SystemSnapshot | null = null;
	private statusUnsub: (() => void) | null = null;

	isPending = false;
	error: Error | null = null;

	constructor(
		host: ReactiveControllerHost,
		// biome-ignore lint/suspicious/noExplicitAny: System type varies
		system: SingleModuleSystem<any>,
		statusPlugin?: StatusPlugin,
		requirementType?: string,
	) {
		this.host = host;
		this.system = system;
		this.statusPlugin = statusPlugin;
		this.requirementType = requirementType;
		host.addController(this);
	}

	hostConnected(): void {}

	hostDisconnected(): void {
		this.statusUnsub?.();
		this.statusUnsub = null;
	}

	rollback(): void {
		if (this.snapshot) {
			this.system.restore(this.snapshot);
			this.snapshot = null;
		}
		this.isPending = false;
		this.error = null;
		this.statusUnsub?.();
		this.statusUnsub = null;
		this.host.requestUpdate();
	}

	mutate(updateFn: () => void): void {
		this.snapshot = this.system.getSnapshot();
		this.isPending = true;
		this.error = null;
		this.system.batch(updateFn);
		this.host.requestUpdate();

		if (this.statusPlugin && this.requirementType) {
			this.statusUnsub?.();
			this.statusUnsub = this.statusPlugin.subscribe(() => {
				const status = this.statusPlugin!.getStatus(this.requirementType!);
				if (!status.isLoading && !status.hasError) {
					this.snapshot = null;
					this.isPending = false;
					this.statusUnsub?.();
					this.statusUnsub = null;
					this.host.requestUpdate();
				} else if (status.hasError) {
					this.error = status.lastError;
					this.rollback();
				}
			});
		}
	}
}

/**
 * Reactive controller that creates and manages a Directive system.
 * The system is automatically started when the host connects and destroyed when it disconnects.
 */
export class SystemController<M extends ModuleSchema> implements ReactiveController {
	private options: ModuleDef<M> | CreateSystemOptionsSingle<M>;
	private _system: SingleModuleSystem<M> | null = null;

	constructor(host: ReactiveControllerHost, options: ModuleDef<M> | CreateSystemOptionsSingle<M>) {
		this.options = options;
		host.addController(this);
	}

	get system(): SingleModuleSystem<M> {
		if (!this._system) {
			throw new Error(
				"[Directive] SystemController.system is not available. " +
				"This can happen if:\n" +
				"  1. Accessed before hostConnected (e.g., in a class field initializer)\n" +
				"  2. Accessed after hostDisconnected (system was destroyed)\n" +
				"Solution: Access system only in lifecycle methods (connectedCallback, render) " +
				"or after the element is connected to the DOM.",
			);
		}
		return this._system;
	}

	hostConnected(): void {
		const isModule = "id" in this.options && "schema" in this.options;
		const system = isModule
			? createSystem({ module: this.options as ModuleDef<M> })
			: createSystem(this.options as CreateSystemOptionsSingle<M>);
		this._system = system as unknown as SingleModuleSystem<M>;
		this._system.start();
	}

	hostDisconnected(): void {
		this._system?.destroy();
		this._system = null;
	}
}

/**
 * Module controller — zero-config all-in-one.
 * Creates system, starts it, subscribes to all facts/derivations.
 */
export class ModuleController<M extends ModuleSchema> implements ReactiveController {
	private host: ReactiveControllerHost;
	private moduleDef: ModuleDef<M>;
	private config?: {
		// biome-ignore lint/suspicious/noExplicitAny: Plugin types vary
		plugins?: Plugin<any>[];
		debug?: DebugConfig;
		errorBoundary?: ErrorBoundaryConfig;
		tickMs?: number;
		zeroConfig?: boolean;
		// biome-ignore lint/suspicious/noExplicitAny: Facts type varies
		initialFacts?: Record<string, any>;
		status?: boolean;
	};

	private _system: SingleModuleSystem<M> | null = null;
	private unsubFacts?: () => void;
	private unsubDerived?: () => void;

	facts: InferFacts<M> = {} as InferFacts<M>;
	derived: InferDerivations<M> = {} as InferDerivations<M>;
	statusPlugin?: StatusPlugin;

	get system(): SingleModuleSystem<M> {
		if (!this._system) {
			throw new Error("[Directive] ModuleController.system is not available before hostConnected.");
		}
		return this._system;
	}

	get events(): SingleModuleSystem<M>["events"] {
		return this.system.events;
	}

	constructor(
		host: ReactiveControllerHost,
		moduleDef: ModuleDef<M>,
		config?: {
			// biome-ignore lint/suspicious/noExplicitAny: Plugin types vary
			plugins?: Plugin<any>[];
			debug?: DebugConfig;
			errorBoundary?: ErrorBoundaryConfig;
			tickMs?: number;
			zeroConfig?: boolean;
			// biome-ignore lint/suspicious/noExplicitAny: Facts type varies
			initialFacts?: Record<string, any>;
			status?: boolean;
		},
	) {
		this.host = host;
		this.moduleDef = moduleDef;
		this.config = config;
		host.addController(this);
	}

	hostConnected(): void {
		const allPlugins = [...(this.config?.plugins ?? [])];

		if (this.config?.status) {
			const sp = createRequirementStatusPlugin();
			this.statusPlugin = sp;
			// biome-ignore lint/suspicious/noExplicitAny: Plugin generic issues
			allPlugins.push(sp.plugin as Plugin<any>);
		}

		// biome-ignore lint/suspicious/noExplicitAny: Required for overload compatibility
		const system = createSystem({
			module: this.moduleDef,
			plugins: allPlugins.length > 0 ? allPlugins : undefined,
			debug: this.config?.debug,
			errorBoundary: this.config?.errorBoundary,
			tickMs: this.config?.tickMs,
			zeroConfig: this.config?.zeroConfig,
			initialFacts: this.config?.initialFacts,
		} as any) as unknown as SingleModuleSystem<M>;

		this._system = system;
		system.start();

		// Subscribe to all facts
		this.facts = system.facts.$store.toObject() as InferFacts<M>;
		this.unsubFacts = system.facts.$store.subscribeAll(() => {
			this.facts = system.facts.$store.toObject() as InferFacts<M>;
			this.host.requestUpdate();
		});

		// Subscribe to all derivations
		const derivationKeys = Object.keys(system.derive ?? {});
		const getDerived = (): InferDerivations<M> => {
			const result: Record<string, unknown> = {};
			for (const key of derivationKeys) {
				result[key] = system.read(key);
			}
			return result as InferDerivations<M>;
		};
		this.derived = getDerived();

		if (derivationKeys.length > 0) {
			this.unsubDerived = system.subscribe(derivationKeys, () => {
				this.derived = getDerived();
				this.host.requestUpdate();
			});
		}
	}

	hostDisconnected(): void {
		this.unsubFacts?.();
		this.unsubDerived?.();
		this._system?.destroy();
		this._system = null;
	}

	dispatch(event: InferEvents<M>): void {
		this.system.dispatch(event);
	}
}

// ============================================================================
// Factory Functions (active)
// ============================================================================

export function createDerived<T>(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	key: string | string[],
): DerivedController<T> {
	return new DerivedController<T>(host, system, key);
}

export function createFact<T>(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	factKey: string,
): FactController<T> {
	return new FactController<T>(host, system, factKey);
}

/**
 * Create an inspect controller.
 * Returns InspectState; pass `{ throttleMs }` for throttled updates.
 */
export function createInspect(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	options?: { throttleMs?: number },
): InspectController {
	return new InspectController(host, system, options);
}

export function createRequirementStatus(
	host: ReactiveControllerHost,
	statusPlugin: StatusPlugin,
	type: string,
): RequirementStatusController {
	return new RequirementStatusController(host, statusPlugin, type);
}

export function createWatch<T>(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	derivationId: string,
	callback: (newValue: T, previousValue: T | undefined) => void,
): WatchController<T> {
	return new WatchController<T>(host, system, derivationId, callback);
}

export function createDirectiveSelector<R>(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	selector: (state: Record<string, unknown>) => R,
	equalityFn: (a: R, b: R) => boolean = defaultEquality,
	options?: { autoTrack?: boolean },
): DirectiveSelectorController<R> {
	return new DirectiveSelectorController<R>(host, system, selector, equalityFn, options);
}

export function createExplain(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	requirementId: string,
): ExplainController {
	return new ExplainController(host, system, requirementId);
}

export function createConstraintStatus(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	constraintId?: string,
): ConstraintStatusController {
	return new ConstraintStatusController(host, system, constraintId);
}

export function createOptimisticUpdate(
	host: ReactiveControllerHost,
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	statusPlugin?: StatusPlugin,
	requirementType?: string,
): OptimisticUpdateController {
	return new OptimisticUpdateController(host, system, statusPlugin, requirementType);
}

export function createModule<M extends ModuleSchema>(
	host: ReactiveControllerHost,
	moduleDef: ModuleDef<M>,
	config?: {
		// biome-ignore lint/suspicious/noExplicitAny: Plugin types vary
		plugins?: Plugin<any>[];
		debug?: DebugConfig;
		errorBoundary?: ErrorBoundaryConfig;
		tickMs?: number;
		zeroConfig?: boolean;
		// biome-ignore lint/suspicious/noExplicitAny: Facts type varies
		initialFacts?: Record<string, any>;
		status?: boolean;
	},
): ModuleController<M> {
	return new ModuleController<M>(host, moduleDef, config);
}

// ============================================================================
// Functional Helpers
// ============================================================================

export function useDispatch<M extends ModuleSchema = ModuleSchema>(
	system: SingleModuleSystem<M>,
): (event: InferEvents<M>) => void {
	assertSystem("useDispatch", system);
	return (event: InferEvents<M>) => {
		system.dispatch(event);
	};
}

/**
 * Returns the system's events dispatcher.
 */
export function useEvents<M extends ModuleSchema = ModuleSchema>(
	system: SingleModuleSystem<M>,
): SingleModuleSystem<M>["events"] {
	assertSystem("useEvents", system);
	return system.events;
}

/**
 * Reactive controller for time-travel state.
 * Triggers host updates when snapshots change or navigation occurs.
 *
 * @example
 * ```typescript
 * class MyElement extends LitElement {
 *   private tt = new TimeTravelController(this, system);
 *   render() {
 *     const { canUndo, undo } = this.tt.value ?? {};
 *     return html`<button ?disabled=${!canUndo} @click=${undo}>Undo</button>`;
 *   }
 * }
 * ```
 */
export class TimeTravelController implements ReactiveController {
	value: TimeTravelState | null = null;
	private _unsub?: () => void;

	constructor(
		private _host: ReactiveControllerHost,
		// biome-ignore lint/suspicious/noExplicitAny: System type varies
		private _system: SingleModuleSystem<any>,
	) {
		this._host.addController(this);
	}

	hostConnected(): void {
		this.value = buildTimeTravelState(this._system);
		this._unsub = this._system.onTimeTravelChange(() => {
			this.value = buildTimeTravelState(this._system);
			this._host.requestUpdate();
		});
	}

	hostDisconnected(): void {
		this._unsub?.();
		this._unsub = undefined;
	}
}

/**
 * Functional helper for time-travel state (non-reactive, snapshot).
 * For reactive updates, use TimeTravelController.
 */
// biome-ignore lint/suspicious/noExplicitAny: System type varies
export function useTimeTravel(system: SingleModuleSystem<any>): TimeTravelState | null {
	assertSystem("useTimeTravel", system);
	return buildTimeTravelState(system);
}

export function getDerived<T>(
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	derivationId: string,
): () => T {
	return () => system.read(derivationId) as T;
}

export function getFact<T>(
	// biome-ignore lint/suspicious/noExplicitAny: System type varies
	system: SingleModuleSystem<any>,
	factKey: string,
): () => T | undefined {
	return () => system.facts.$store.get(factKey) as T | undefined;
}

// ============================================================================
// Typed Hooks Factory
// ============================================================================

export function createTypedHooks<M extends ModuleSchema>(): {
	createDerived: <K extends keyof InferDerivations<M>>(
		host: ReactiveControllerHost,
		system: SingleModuleSystem<M>,
		derivationId: K,
	) => DerivedController<InferDerivations<M>[K]>;
	createFact: <K extends keyof InferFacts<M>>(
		host: ReactiveControllerHost,
		system: SingleModuleSystem<M>,
		factKey: K,
	) => FactController<InferFacts<M>[K]>;
	useDispatch: (system: SingleModuleSystem<M>) => (event: InferEvents<M>) => void;
	useEvents: (system: SingleModuleSystem<M>) => SingleModuleSystem<M>["events"];
	createWatch: <K extends string>(
		host: ReactiveControllerHost,
		system: SingleModuleSystem<M>,
		key: K,
		callback: (newValue: unknown, previousValue: unknown) => void,
	) => WatchController<unknown>;
} {
	return {
		createDerived: <K extends keyof InferDerivations<M>>(
			host: ReactiveControllerHost,
			system: SingleModuleSystem<M>,
			derivationId: K,
		) => createDerived<InferDerivations<M>[K]>(host, system, derivationId as string),
		createFact: <K extends keyof InferFacts<M>>(
			host: ReactiveControllerHost,
			system: SingleModuleSystem<M>,
			factKey: K,
		) => createFact<InferFacts<M>[K]>(host, system, factKey as string),
		useDispatch: (system: SingleModuleSystem<M>) => {
			return (event: InferEvents<M>) => {
				system.dispatch(event);
			};
		},
		useEvents: (system: SingleModuleSystem<M>) => system.events,
		createWatch: <K extends string>(
			host: ReactiveControllerHost,
			system: SingleModuleSystem<M>,
			key: K,
			callback: (newValue: unknown, previousValue: unknown) => void,
		) => createWatch<unknown>(host, system, key, callback),
	};
}
